### ISSUE TITLE
ViewPager card distance

### ISSUE THREAD

**Issue by CedricVandelaer** [rubensousa/ViewPagerCards#10]
Hi, great tutorial you wrote!

I was wondering if it's possible to increase the distance between the fragments in the viewpager?

**Comment by rubensousa** [comment]
Just increase the padding (start and end) and it should work.

**Comment by CedricVandelaer** [comment]
I have done this, but this seems to increase/decrease the width of the fragment but not the space in between the fragments

**Comment by rubensousa** [comment]
I meant margin, sorry. The padding will only increase/decrease the width of the card.

**Comment by rubensousa** [comment]
But you need to do this in the adapter itself, not in the viewpager

**Comment by CedricVandelaer** [comment]
This did not work either, I don't really know why. My fragments are just CardViews at the root of the view and giving them a margin did not change anything.

I did found a solution however by using:
`mViewPager.setPageMargin((int)ScreenUtils.dpToPixels(this, 16));
`
But thanks for the help :)
