### ISSUE TITLE
Display multiple view-pages at the same time. 

### ISSUE THREAD

**Issue by prashant-webonise** [rubensousa/ViewPagerCards#2]
Hi,

Thank you for the lovely implementation.
I was trying around with the code aiming to display 2 or more views at the same time and all the centre views having scaling enables. 

I tried with
@Override
    public float getPageWidth(int position) {
        return super.getPageWidth(position) / 2;
    }

in the adapter, but it isn't working as intended.

So if you get a chance to look into this, do share.
Thanks

**Comment by rubensousa** [comment]
Have you tried adding dummy items and setting them to invisible?
If you're trying to show a lot of items, I wouldn't recommend a ViewPager though.

**Comment by rubensousa** [comment]
I'm closing this, since it's more like a feature request, and not an issue with the sample.
